# java 17
FROM eclipse-temurin:17-jdk

# working directory
WORKDIR /app

# Copy your pre-built JAR
COPY RecipeAPI-0.0.1-SNAPSHOT.jar app.jar


EXPOSE 8080

# Command to run the JAR
CMD ["java", "-jar", "app.jar"]